name: calculator
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  handy_window: ^0.3.0
  intl: ^0.18.0
  math_expressions: ^2.4.0
  meta: ^1.8.0
  provider: ^6.0.5
  yaru: ^0.5.0
  yaru_icons: ^1.0.1
  yaru_widgets: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
