name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  bundle:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: beta
      - run: sudo apt update
      - run: sudo apt install -y clang cmake curl libgtk-3-dev ninja-build pkg-config unzip xvfb
        env:
          DEBIAN_FRONTEND: noninteractive
      - run: flutter pub get
      - run: flutter build linux -v

  snap:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - run: sudo snap install --classic flutter
      - run: flutter channel main
      - run: flutter pub get
      - run: flutter build linux -v
